In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
dict={
    "name":["kartikey", "parth", "mayur"],
    "marks":[90, 70, 60],
    "city": ["meerut", "itawa", "nukhlow"]
}

In [4]:
dict

{'name': ['kartikey', 'parth', 'mayur'],
 'marks': [90, 70, 60],
 'city': ['meerut', 'itawa', 'nukhlow']}

In [5]:
print(dict)

{'name': ['kartikey', 'parth', 'mayur'], 'marks': [90, 70, 60], 'city': ['meerut', 'itawa', 'nukhlow']}


In [6]:
df=pd.DataFrame(dict)

In [7]:
df

name  marks     city
0  kartikey     90   meerut
1     parth     70    itawa
2     mayur     60  nukhlow

In [8]:
df.to_csv('frnd.csv')

In [10]:
df.to_csv('frnd_no_id.csv', index=False)

In [11]:
df.head(2)

name  marks    city
0  kartikey     90  meerut
1     parth     70   itawa

In [12]:
df.tail(2)

name  marks     city
1  parth     70    itawa
2  mayur     60  nukhlow

In [13]:
df.describe()

marks
count   3.000000
mean   73.333333
std    15.275252
min    60.000000
25%    65.000000
50%    70.000000
75%    80.000000
max    90.000000

In [14]:
reading = pd.read_csv('frnd_no_id.csv')

In [15]:
reading

name  marks     city
0  kartikey     90   meerut
1     parth     70    itawa
2     mayur     60  nukhlow

In [18]:
read = pd.read_csv('hello.csv')

In [19]:
read

Unnamed: 0      srno    marks    train
0           0         1        2        3
1           1        89       67       90
2           2  shatabdi  sleeper  express

In [21]:
read = pd.read_csv('hello.csv')

In [22]:
read

srno    marks    train
0         1        2        3
1        89       67       90
2  shatabdi  sleeper  express

In [24]:
ser = pd.Series(np.random.rand(10))

In [25]:
ser

0    0.370144
1    0.399049
2    0.903952
3    0.761314
4    0.464328
5    0.229130
6    0.728491
7    0.350883
8    0.525123
9    0.853769
dtype: float64

In [26]:
type(ser)

pandas.core.series.Series

In [27]:
newd = pd.DataFrame(np.random.rand(200,6), index = np.arange(200))

In [28]:
newd.head()

0         1         2         3         4         5
0  0.187693  0.079877  0.804932  0.989309  0.936360  0.711707
1  0.164144  0.466536  0.691674  0.775749  0.339032  0.301943
2  0.518774  0.831544  0.122554  0.919860  0.583732  0.734127
3  0.623732  0.746848  0.829377  0.891357  0.955498  0.373421
4  0.864137  0.676161  0.509677  0.013312  0.972337  0.231098

In [29]:
newd

0         1         2         3         4         5
0    0.187693  0.079877  0.804932  0.989309  0.936360  0.711707
1    0.164144  0.466536  0.691674  0.775749  0.339032  0.301943
2    0.518774  0.831544  0.122554  0.919860  0.583732  0.734127
3    0.623732  0.746848  0.829377  0.891357  0.955498  0.373421
4    0.864137  0.676161  0.509677  0.013312  0.972337  0.231098
..        ...       ...       ...       ...       ...       ...
195  0.471139  0.718594  0.633344  0.499881  0.729514  0.285077
196  0.320563  0.662487  0.561201  0.297960  0.250979  0.392272
197  0.295961  0.692571  0.430656  0.937713  0.815417  0.061469
198  0.980172  0.712474  0.355960  0.453687  0.919053  0.055522
199  0.383665  0.800142  0.097129  0.226487  0.835683  0.342510

[200 rows x 6 columns]

In [30]:
newd[0][0]="kartikey"

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15860\2900556483.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newd[0][0]="kartikey"
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15860\2900556483.py:1: FutureWarning: Setting an item of inc

In [31]:
newd.head()

0         1         2         3         4         5
0  kartikey  0.079877  0.804932  0.989309  0.936360  0.711707
1  0.164144  0.466536  0.691674  0.775749  0.339032  0.301943
2  0.518774  0.831544  0.122554  0.919860  0.583732  0.734127
3  0.623732  0.746848  0.829377  0.891357  0.955498  0.373421
4  0.864137  0.676161  0.509677  0.013312  0.972337  0.231098

In [33]:
newd.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
5    float64
dtype: object

In [34]:
l=[1,2,4,5,6]

In [36]:
pd.Series(l)

0    1
1    2
2    4
3    5
4    6
dtype: int64

In [37]:
pd.Series(l[3])

0    5
dtype: int64

In [38]:
l

[1, 2, 4, 5, 6]

In [41]:
p=pd.Series(l, index=["v","w","x", "y","z"])

In [42]:
p

v    1
w    2
x    4
y    5
z    6
dtype: int64

In [43]:
a=pd.Series(data=[1,2,3,4,np.NaN])

In [44]:
a

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [45]:
len(a)

5

In [46]:
a.count()

4

In [50]:
a.hasnans

True

In [51]:
a.empty, a.hasnans

(False, True)

In [52]:
a.ndim

1

In [55]:
a.nbytes

40

In [56]:
a.size

5

In [5]:
dict

{'name': ['kartikey', 'parth', 'mayur'],
 'marks': [90, 70, 60],
 'city': ['meerut', 'itawa', 'nukhlow']}

In [6]:
df=pd.DataFrame(dict)

In [8]:
df

name  marks     city
0  kartikey     90   meerut
1     parth     70    itawa
2     mayur     60  nukhlow

In [15]:
df.to_csv('helloji.csv', index=False)

In [24]:
pd.read_csv('helloji.csv')

name  marks     city
0  kartikey     90   meerut
1     parth     70    itawa
2     mayur     60  nukhlow

In [25]:
er

name  marks     city
0  kartikey     90   meerut
1     parth     70    itawa
2     mayur     60  nukhlow

In [26]:
df

name  marks     city
0  kartikey     90   meerut
1     parth     70    itawa
2     mayur     60  nukhlow

In [27]:
df.to_excel('helex.xlsx', index=False)

In [28]:
pd.read_excel('helex.xlsx')

name  marks     city
0  kartikey     90   meerut
1     parth     70    itawa
2     mayur     60  nukhlow

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   marks   3 non-null      int64 
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [31]:
df.columns

Index(['name', 'marks', 'city'], dtype='object')

In [33]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [35]:
df.columns=list('ABC')

In [36]:
df

A   B        C
0  kartikey  90   meerut
1     parth  70    itawa
2     mayur  60  nukhlow

In [37]:
df.index=list('123')

In [38]:
df

A   B        C
1  kartikey  90   meerut
2     parth  70    itawa
3     mayur  60  nukhlow

In [40]:
er

name  marks     city
0  kartikey     90   meerut
1     parth     70    itawa
2     mayur     60  nukhlow

In [41]:
df

A   B        C
1  kartikey  90   meerut
2     parth  70    itawa
3     mayur  60  nukhlow

In [42]:
er

name  marks     city
0  kartikey     90   meerut
1     parth     70    itawa
2     mayur     60  nukhlow

In [45]:
er.loc[[0], :]

name  marks    city
0  kartikey     90  meerut

In [46]:
er.loc[:,["name"]]

name
0  kartikey
1     parth
2     mayur

In [49]:
df.isnull()

A      B      C
1  False  False  False
2  False  False  False
3  False  False  False

In [50]:
df

A   B        C
1  kartikey  90   meerut
2     parth  70    itawa
3     mayur  60  nukhlow

In [51]:
df.notnull()

A     B     C
1  True  True  True
2  True  True  True
3  True  True  True

In [52]:
df.T

1      2        3
A  kartikey  parth    mayur
B        90     70       60
C    meerut  itawa  nukhlow

In [53]:
df

A   B        C
1  kartikey  90   meerut
2     parth  70    itawa
3     mayur  60  nukhlow

In [54]:
n=np.array([1,2,3,4,5])

In [55]:
n

array([1, 2, 3, 4, 5])

In [56]:
n.ndim

1

In [57]:
n.T

array([1, 2, 3, 4, 5])

In [58]:
n.size

5

In [60]:
n.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [61]:
n

array([1, 2, 3, 4, 5])

In [62]:
h=1+3j

In [63]:
h

(1+3j)

In [64]:
type(h)

complex