In [3]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
np.arange(1,4)

array([1, 2, 3])

In [6]:
rng=np.arange(1,20)

In [7]:
print(rng)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
rng

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
np.zeroes(5)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [12]:
arrey=np.zeros(5)

In [11]:
print(arrey)

[0. 0. 0. 0. 0.]


In [1]:
list=[[1,2,3], [4,5,6], [7,8,9]]

In [5]:
arr=np.array(list)

In [6]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
sum(np.axis(0))

AttributeError: module 'numpy' has no attribute 'axis'

In [8]:
arr.sum(axis=0)

array([12, 15, 18])

In [9]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [10]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
for i in arr:

SyntaxError: incomplete input (3028108643.py, line 1)

In [12]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [13]:
arr.ndim

2

In [14]:
arr.size

9

In [15]:
arr.nbytes

36

In [16]:
arr.argmax()

8

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [19]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr.reshape(1,1)

ValueError: cannot reshape array of size 9 into shape (1,1)

In [21]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
arr.argmin()

0

In [25]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [26]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [27]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [28]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [31]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
arr2=np.array([[1, 4, 3],
       [4, 8, 6],
       [7, 0, 9]])

In [33]:
arr2

array([[1, 4, 3],
       [4, 8, 6],
       [7, 0, 9]])

In [34]:
arr+arr2

array([[ 2,  6,  6],
       [ 8, 13, 12],
       [14,  8, 18]])

In [35]:
arr3=arr+arr2

In [36]:
arr3

array([[ 2,  6,  6],
       [ 8, 13, 12],
       [14,  8, 18]])

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2

array([[1, 4, 3],
       [4, 8, 6],
       [7, 0, 9]])

In [39]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [40]:
arr.sum()

45

In [41]:
arr.sum

<function ndarray.sum>

In [42]:
arr.min()

1

In [43]:
arr.max()

9

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr[1,2]=0

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])